# Dockerfile for rebuilding a PyKaldi image on a non-master branch
FROM pykaldi/pykaldi:latest

# Copy pykaldi directory into the container
COPY . /pykaldi_travis

# Install PyKaldi
RUN cd /pykaldi \
    && git fetch /pykaldi_travis \
    && git checkout FETCH_HEAD \
    && pip uninstall -y pykaldi \
    && python setup.py install
