# Dockerfile for building PyKaldi image from PyKaldi dependencies image
FROM pykaldi/pykaldi:latest

# Copy pykaldi directory into the container
COPY . /pykaldi_travis

# Install PyKaldi
RUN cd /pykaldi \
	&& git remote add travis /pykaldi_travis \
	&& git fetch travis \
	&& git checkout temp \
	&& python setup.py install \
	&& git remote rm travis \
	&& rm /pykaldi_travis \