# Dockerfile for building pykaldi image from pykaldi-min image
FROM pykaldi/pykaldi-min:latest

# Copy pykaldi directory into the container
COPY . /pykaldi_travis

# Install PyKaldi
RUN cd /pykaldi \
	&& git pull /pykaldi_travis \
	&& python setup.py develop --uninstall \
	&& find kaldi -name "*.so" -delete \
	&& python setup.py develop \
	&& rm -rf /pykaldi_travis
