# Dockerfile for building PyKaldi image from PyKaldi dependencies image
FROM pykaldi/pykaldi-min:latest

# Copy pykaldi directory into the container
COPY . /pykaldi_travis

# Install PyKaldi
RUN cd /pykaldi \
	&& git fetch /pykaldi_travis \
	&& git checkout FETCH_HEAD \
	&& pip uninstall -y pykaldi \
	&& python setup.py install \
	&& rm -rf /pykaldi_travis