# Dockerfile for building PyKaldi image from PyKaldi dependencies image
FROM pykaldi/pykaldi-deps:latest

# Copy pykaldi directory into the container
COPY . /pykaldi

# Install PyKaldi
RUN cd /pykaldi/tools \
    && ln -s /tools/protobuf protobuf \
    && ln -s /tools/clif clif \
    && ln -s /tools/clif_backend clif_backend \
    && ln -s /tools/kaldi kaldi \
    && cd .. \
    && python setup.py install
