# Dockerfile for rebuilding PyKaldi image on master branch
FROM pykaldi/pykaldi:latest

# Copy pykaldi directory into the container
COPY . /pykaldi_travis

# Install PyKaldi
RUN cd /pykaldi \
    && git pull /pykaldi_travis \
    && pip uninstall -y pykaldi \
    && rm -rf build \
    && python setup.py install \
    && rm -rf dist pykaldi.egg-info /pykaldi_travis
