#!/bin/sh

# This script is used for adding using directives to cc files generated by CLIF.

cc=$1
shift
for namespace in "$@"; do
  sed -i.bak "s/using namespace clif;$/using namespace clif;\nusing namespace ${namespace};/g" $cc
  rm -f $cc.bak
done
