<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>clif</string>
	</array>
	<key>name</key>
	<string>Clif</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#types</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>String literal</string>
			<key>end</key>
			<string>\"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_escaped_char</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(namespace)\s+\`</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.namespace.clif</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Clif namespace</string>
			<key>end</key>
			<string>(\`\:)|\s*($\n?|#.*$\n?)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.namespace.begin.clif</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.incorrect-namespace-name.clif</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.namespace.clif</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?=[[:alpha:]_][[:alnum:]_]*)</string>
					<key>contentName</key>
					<string>entity.name.type.namespace.clif</string>
					<key>end</key>
					<string>(?![[:alnum:]_])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_escaped_char</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(class)\s+</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.clif</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Clif class</string>
			<key>end</key>
			<string>(\:)|\s*($\n?|#.*$\n?)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.class.begin.clif</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.missing-section-begin.clif</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.class.clif</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#Crename</string>
				</dict>
				<dict>
					<key>match</key>
					<string>([[:alpha:]_][[:alnum:]_]*(?=\:|\())</string>
					<key>name</key>
					<string>entity.name.type.class.python.clif</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.inheritance.begin.clif</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\)|:)</string>
					<key>name</key>
					<string>meta.class.inheritance.python</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?&lt;=\(|,)\s*</string>
							<key>contentName</key>
							<string>entity.other.inherited-class.clif</string>
							<key>end</key>
							<string>\s*(?:(,)|(?=\)))</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.inheritance.clif</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>$self</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(def)\s+</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.clif</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Clif functions</string>
			<key>end</key>
			<string>($\n?)</string>
			<key>name</key>
			<string>meta.function.clif</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#Crename</string>
				</dict>
				<dict>
					<key>match</key>
					<string>([[:alpha:]_][[:alnum:]_]*(?=\())</string>
					<key>name</key>
					<string>entity.name.function.clif</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.begin.clif</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(self)</string>
							<key>name</key>
							<string>variable.parameter.parameter.function.language.clif</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(,)</string>
							<key>name</key>
							<string>punctuation.separator.parameters.clif</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>([[:alpha:]_][[:alnum:]_]*)\s*(\:)(?!\:)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>meta.function-call.arguments.clif</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.assignment.clif</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\s*(?=(,)|\))</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#Crename</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#types</string>
								</dict>
								<dict>
									<key>begin</key>
									<string>\s*(\=)\s*</string>
									<key>beginCaptures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>keyword.operator.assignment.clif</string>
										</dict>
									</dict>
									<key>end</key>
									<string>\s*(?=(,)|\))</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>match</key>
											<string>(default)</string>
											<key>name</key>
											<string>variable.parameter.parameter.function.language.clif</string>
										</dict>
										<dict>
											<key>match</key>
											<string>([[:alpha:]_][[:alnum:]_]*)</string>
											<key>name</key>
											<string>variable.parameter.parameter.function.clif</string>
										</dict>
									</array>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(-\&gt;)</string>
					<key>end</key>
					<string>(?=$\n?)</string>
					<key>name</key>
					<string>meta.function.returnvalue.clif</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#types</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\@[[:alpha:]_][[:alnum:]_]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.decorator.clif</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Clif decorator</string>
			<key>end</key>
			<string>($\n?)</string>
			<key>name</key>
			<string>meta.function.decorator.clif</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>Crename</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.single</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.clif</string>
						</dict>
					</dict>
					<key>include</key>
					<string>#types</string>
					<key>match</key>
					<string>(\`([[:alpha:]_][[:alnum:]_]*)(&lt;[[:alpha:]][[:alnum:]_]+&gt;)?(\(\))?\`)\s+(as)</string>
				</dict>
			</array>
		</dict>
		<key>cclass</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>([[:alpha:]][[:alnum:]_]*(&lt;[[:alpha:]][[:alnum:]_]+&gt;)?)</string>
					<key>name</key>
					<string>entity.name.type.class.C.clif</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>#.*</string>
					<key>name</key>
					<string>comment.line.number-sign.clif</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(from|as|import|pass|enum|const)\b</string>
					<key>name</key>
					<string>keyword.operator.control.clif</string>
				</dict>
			</array>
		</dict>
		<key>pythonclass</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>([[:alpha:]][[:alnum:]_]*)</string>
					<key>name</key>
					<string>entity.name.type.class.python.clif</string>
				</dict>
			</array>
		</dict>
		<key>string_escaped_char</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\w*</string>
					<key>name</key>
					<string>constant.character.escape</string>
				</dict>
			</array>
		</dict>
		<key>types</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(int|bytes|str|bool|float|list|tuple|set|dict|object)\b</string>
					<key>name</key>
					<string>support.type.clif</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.clif</string>
	<key>uuid</key>
	<string>67b6678b-acbd-4efc-9cd0-99484cd09ab5</string>
</dict>
</plist>
